config/routes.rb
Rails.application.routes.draw do
  get 'main/index'

  get 'kazuki/index'
  get 'yuki/index'
  get 'yuta/index'
  get 'welcome/index'
  root 'root#index'

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/bunkatuframe_controller.rb
class BunkatuframeController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/kazuki_controller.rb
class KazukiController < ApplicationController
  def index
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/oyabaframe_controller.rb
class BunkatuframeController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/root_controller.rb
class RootController < ApplicationController
  def index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/yuki_controller.rb
class YukiController < ApplicationController
  def index
  end
end

app/controllers/yuta_controller.rb
class YutaController < ApplicationController
  def index
  end
end

app/helpers/kazuki_helper.rb
module KazukiHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/yuki_helper.rb
module YukiHelper
end

app/helpers/yuta_helper.rb
module YutaHelper
end

app/views/main/index.html.erb
<!---<h1>Main#index</h1>
<p>Find me in app/views/main/index.html.erb</p>-->







<FONT face="ＭＳ Ｐ明朝" size="3">
<!--<input type="button" value="+">-->
<!--<form action="#" method="post">
<input type="button" value="+" name="button" onclick="alert('質問作成')" />
</form>
-->
<!--ボタン-->
 <a href="#modal" rel="leanModal"><input type="button" value="+"></a>
  <div id="modal" style="display:none; background:yellow; padding:2em">
 	<div><a class="modal_close" href="#"><input type="button" value="×"></a>
 	</div>
    <!--モーダルウィンドウの中身-->
	<br>
	<B>
	<INPUT type="radio" name="question" value="select"checked>質問
		<pre>
			<br>
			<br>
		</pre>
		<INPUT type="radio" name="question" value="select2">選択
		<br>
		<input type="button" value="新規作成">
		<br>
	</B>
	</div>
<B>
<center>
<pre>数学        3限	火曜</pre>   
</center>          　　　　　　　　
</B>
</FONT><BR>

<!--質問内容-->
<pre>
<hr>
質問～？(質問しない人14/30)
<hr>
A(田村)：～。
Ｂ（東）:～。
先生:Anser：～。
</pre>
<br>
<TEXTAREA cols="50" rows="5" name="puestion">
内容を記入してください。
</TEXTAREA>
<input type="button" value="返信">
<input type="button" value="区切り">

app/views/main/oyaba.html.erb
<!---<h1>Main#index</h1>
<p>Find me in app/views/main/index.html.erb</p>-->







<FONT face="ＭＳ Ｐ明朝" size="3">
<!--<input type="button" value="+">-->
<!--<form action="#" method="post">
<input type="button" value="+" name="button" onclick="alert('質問作成')" />
</form>
-->
<!--ボタン-->
 <a href="#modal" rel="leanModal"><input type="button" value="+"></a>
  <div id="modal" style="display:none; background:yellow; padding:2em">
 	<div><a class="modal_close" href="#"><input type="button" value="×"></a>
 	</div>
 	<%= image_tag("icon_kugiri.jpg", {width: 50})%>
    <!--モーダルウィンドウの中身-->
	<br>
	<B>
	<p> >><a href="#open01">質問</a></p>	
		<br>
		<br>
	<p> >><a href="#open02">４択</a></p>
		<br>
		<br>
	</B>
	</div>
<div id="#open01">
	<span class="modal_window">
	<a href="#" class="closs_overlay">×</a>
	<h2>質問内容設定</h2>
	<p>	質問したいことを入力してください</p>
	<textarea cols="30"rows="5"name="situmon"></textarea>
	<a href="#">ｃｌｏｓｅ</a>
	</span>
</div>

<!-- <center>
<pre>数学        3限	火曜</pre>   
</center>          　　　　　　　　

</FONT><BR> -->

<!--質問内容
<pre>
<hr>
質問～？(質問しない人14/30)
<hr>
A(田村)：～。
Ｂ（東）:～。
先生:Anser：～。
</pre>
<br>
<TEXTAREA cols="50" rows="5" name="puestion">
内容を記入してください。
</TEXTAREA>
<input type="button" value="返信">
<input type="button" value="区切り">
 -->

 -->

app/views/root/index.html.erb
<div class="home">
  <h1>home</h1>
  <ul>
    <li><%= link_to("main", main_index_path) %></li>
    <li><%= link_to("kazuki", kazuki_index_path) %></li>
    <li><%= link_to("yuki",   yuki_index_path)   %></li>
    <li><%= link_to("yuta",   yuta_index_path)   %></li>
  </ul>

  <a href="#modal" rel="leanModal">開く</a>
  <div id="modal" style="display:none; background:white; padding:2em">
    <div><a class="modal_close" href="#">close</a></div>
    hogehogehoge
  </div>

</div>

app/views/welcome/index.html.erb
<h1>Hello rails!</h1>

app/views/yuki/index.html.erb
<h1>Yuki#index</h1>
<p>Find me in app/views/yuki/index.html.erb</p>
aiueo
	<table border="1" cellspacing="15" cellpadding="15">
		<tr>
			<td colspan="3">あいさつ</td>
		</tr>
		<tr>
			<td>Morning</td><td>おはよう</td><td>おは＾＾</td>
		</tr>
		<tr>
		<td>Night</td><td>こんばんわ</td><td>ばんわ＾＾</td>
		</tr>
	</table>

	<frameset cols="150,*">
	</frameset>



	<FORM>
		<H5>cols="30" rows="5"を指定</H5>
		<TEXTAREA cols="30" rows="5" name="com1">

		</TEXTAREA>

		<H5>最初から文字を表示</H5>
		<TEXTAREA cols="20" rows="2" name="com2">
			感想を書く！！
		</TEXTAREA>
	</FORM>
	<FORM>
		<p>
			<INPUT type="submit" value="送信するよ？＾＾" name="go">
		</p>
	</FORM>


	<LI>リンク集</LI>
	<ul>
	<li><p><a HREF="/kazuki/index">しばっさんの好き嫌いについて</A></p></li>
	<li><a HREF="/yuta/index">阿部さんの数字のやつ</A></li>

app/views/yuta/index.html.erb
<!---<title> my hompage </title>-->
<h1>Yuta#index</h1>
<p>Find me in app/views/yuta/index.html.erb</p>
<html>

<head>
<title> my hompage </title>
</head>
<body text = "bule">
 hello!!
 </body>

</html>

<table border="10"width="300" height="100">
<tr>
<th>1</th><th>2</th>
</tr>
	<tr>
	<td>one</td><td>two</td>
	</tr>

	<tr>
	<td>two</td><td>three</td>
	</tr>
</table>
<a href="/kazuki/index">name sibata</a>
<br>

<a href ="/yuki/index"> name yuki</a>

<hr>
<marquee>目</marquee>
<ol>
<li>1つ目のリスト</li>
<li>2つ目のリスト</li>
<li>3つ目のリスト</li>
</ol>
<TEXTAREA cols="20" rows="3" name="one">
	hello!!!!
</TEXTAREA>


<TEXTAREA cols="20" rows="3" name="one" readonly>
	nothing
</TEXTAREA>
<br>
男<INPUT type="radio" name="ichiro" value="man">
<br>
<INPUT type="submit" name="ssss" value="ボタンに表示するテキスト">