easkver2/config/routes.rb
Rails.application.routes.draw do

resources :projects do 
  resources :tasks,only: [:create, :destroy]
end

resources :project2s do 
  resources :task2s,only: [:create, :destroy]
end
 post '/projects/:project_id/toggle' => 'projects#toggle'

root 'projects#index'

end

easkver2/app/models/project.rb
class Project < ActiveRecord::Base
	has_many :tasks
	validates :title, presence: {message:"入力してください"}
	 validates :title, length: { minimum: 3 ,message: "短い"}
end

easkver2/app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  validates :title, presence: true
  scope :unfinished, ->{ where(done: false) }
end

easkver2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

easkver2/app/controllers/project2s_controller.rb
class Project2sController < ApplicationController

	before_action :set_project,only: [:show, :edit, :update, :destroy]


	def index
		@projects = Project.all
	end

	def show

	end

	def create
		@project = Project.new(project_params)
		if 	@project.save
			redirect_to projects_path
		else
			render 'new'
		end
	end

	def edit
	
	end

	def update
	
		if @project.update(project_params)
			redirect_to project_path
		else
			render 'edit'
		end
	end

	def destroy
		
		@project.destroy
		redirect_to projects_path
	end
	def toggle
		render nothing: true
		p params[:project_id], "deback"
		@project = Project.find(params[:project_id])
		@project.nty = @project.nty + 1
		@project.save
	end



private
	def project_params
		params[:project].permit(:title)
	end

	def set_project
		@project = Project.find(params[:id])
	end

end

easkver2/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

	before_action :set_project,only: [:show, :edit, :update, :destroy]


	def index
		@projects = Project.all
	end

	def show

	end
	def new
		@project = Project.new
	end

	def create
		@project = Project.new(project_params)
		if 	@project.save
			redirect_to projects_path
		else
			render 'new'
		end
	end

	def edit
	
	end

	def update
	
		if @project.update(project_params)
			redirect_to project_path
		else
			render 'edit'
		end
	end

	def destroy
		
		@project.destroy
		redirect_to projects_path
	end
	def toggle
		render nothing: true
		p params[:project_id], "deback"
		@project = Project.find(params[:project_id])
		@project.nty = @project.nty + 1
		@project.save
	end



private
	def project_params
		params[:project].permit(:title)
	end

	def set_project
		@project = Project.find(params[:id])
	end

end

easkver2/app/controllers/task2s_controller.rb
class Task2sController < ApplicationController

	def create
		@project = Project.find(params[:project_id])
		@task = @project.tasks.create(tasks_params)
		redirect_to project_path(@project.id)
	end

	def destroy	
		@task = Task.find(params[:id])
		@task.destroy
		redirect_to projects_path
	end



	private
	def tasks_params
		params[:task].permit(:title)
	end

end

easkver2/app/controllers/tasks_controller.rb
class TasksController < ApplicationController

	def create
		@project = Project.find(params[:project_id])
		@task = @project.tasks.create(tasks_params)
		redirect_to project_path(@project.id)
	end

	def destroy	
		@task = Task.find(params[:id])
		@task.destroy
		redirect_to projects_path
	end



	private
	def tasks_params
		params[:task].permit(:title)
	end

end

easkver2/app/helpers/application_helper.rb
module ApplicationHelper
end

easkver2/app/helpers/projects_helper.rb
module ProjectsHelper
end

easkver2/app/helpers/tasks_helper.rb
module TasksHelper
end

easkver2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Eask</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "application", media: "all" %>

  <%= csrf_meta_tags %>
</head>
<body>

<div class="header">
    <A href="http://172.16.30.14:3000/"><%= image_tag("icon_home.jpg", {width: 50})%></A>
    <%= image_tag("icon_line.jpg", {width: 50})%>eask ver.0.1.4

  </div>
  <div class="main">
    <%= yield %>
  </div>
</body>
</html>

easkver2/app/views/project2s/_form.html.erb
<%= form_for@project do |f| %>

<p>

	<br>
	<%= f.text_field :title %>
	<% if @project.errors.any? %>
	<%= @project.errors.messages[:title][0] %>
	<% end%>

</p>
<p>
	<%= f.submit value:"作戦開始"%>
</p>



<% end %>

easkver2/app/views/project2s/edit.html.erb
<h1>変更</h1>
<h2>既存の質問を変更する画面です。<br>
	<hr color ="pink">
	※入力されている回答はそのままです。</h2>
<%= render'form' %> 

easkver2/app/views/project2s/index.html.erb
<h1>質問一覧</h1>

<ul>
<%= link_to "[新規作成]", new_project_path %>
	<p>質問をクリックすると回答ができます。</p>
	<hr color ="pink">
	<% @projects.each do |project| %>
	<%= project.id %>.[<%= link_to project.title ,project_path(project.id)%>] 
	(回答数：<%= project.tasks.count%>)(pass：<%= project.nty %>)
		<div align= "right"><%= link_to "[編集]",edit_project_path(project.id)%>
		<%= link_to "[削除]",project_path(project.id), method: :delete,data:{confirm:"削除しますか？"} %></div>
	<hr color ="pink">
	<% end %>


</ul>

easkver2/app/views/project2s/new.html.erb
<h1>新規作成</h1>
<h2>ここでは新規作成ができます</h2>
<%= render'form' %> 

easkver2/app/views/project2s/show.html.erb
<h1><%= @project.title  %>
	<from>
		<input type="button" value="pass">
	</from></h1>

<ul>
<% @project.tasks.each do |task| %>
<li>
	<%= task.title %>

	<%= link_to "[回答削除]",project_task_path(task.project_id,task.id), method: :delete,data:{confirm:"削除しますか？"} %>
	<br>
	<hr color ="pink">
</li>
	<%end%>
<li>
	<%= form_for [@project, @project.tasks.build] do |f| %>
</li>
	<%= f.text_field :title %>
	<%= f.submit value:"回答作成" %>
	<%end%>

<script>
$(function(){
	$("input[type = button]").click(function(){
		$.post('/projects/<%= @project.id  %>/toggle');
	});
});
</script>

</ul>

easkver2/app/views/projects/edit.html.erb
<h1>変更</h1>
<h2>既存の質問を変更する画面です。<br>
	<hr color ="pink">
	※入力されている回答はそのままです。</h2>
<%= render'form' %> 
<%= link_to "[質問一覧へ]", projects_path %>

easkver2/app/views/projects/new.html.erb
<h1>新規作成</h1>
<h2>ここでは新規作成ができます</h2>
<%= render'form' %> 
<%= link_to "[質問一覧へ]", projects_path %>

easkver2/app/views/projects/show.html.erb
<h1><%= @project.title  %>
	<form>
		<input type="button" value="pass">
	</form></h1>

<ul>
<% @project.tasks.each do |task| %>
<li>
	<%= task.title %>

	<%= link_to "[回答削除]",project_task_path(task.project_id,task.id), method: :delete,data:{confirm:"削除しますか？"} %>
	<br>
	<hr color ="pink">
</li>
	<%end%>
<li>
	<%= form_for [@project, @project.tasks.build] do |f| %>
</li>
	<%= f.text_field :title %>
	<%= f.submit value:"回答作成" %>
	<%end%>

<script>
$(function(){
	$("input[type = button]").click(function(){
		$.post('/projects/<%= @project.id  %>/toggle');
	});
});
</script>

</ul>
<%= link_to "[質問一覧へ]", projects_path %>